# -*- coding: utf-8 -*-
"""Logistic_Regression_Example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10aL3-Q5ngpn0h3MmHOgef-rwddcSd9ZT
"""

#Import the libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#Import the Dataset
data = pd.read_csv('breast_cancer.csv', header='infer')
data.head()

X = data.iloc[:,1:-1]
y = data.iloc[:,-1]

#Splitting the  data in train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

#LogisitcRegression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=0)
lr.fit(X_train, y_train)

#Predict the X_test outcomes
y_pred = lr.predict(X_test)

#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

#Accuracy for Regression
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator=lr, X=X_train, y=y_train, cv=10)
print(accuracy.mean()*100)

print((accuracy.std()*100))

