# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DLK9SJ5zHEAI2-pyJ_tEf2fLNdYpXqwj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('Position_Salaries.csv', header='infer')
X = data.iloc[:,1:-1].values
y = data.iloc[:,-1].values

#Implementing Decision Tree using SKLEARN
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X, y)

y_pred = regressor.predict(X)
y_pred

regressor.predict([[6.5]])

#HIGHRESOLUTION VISUALIZATION
X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='blue')
plt.plot(X_grid, regressor.predict(X_grid), color='red')

#Hence not a best Option for single independent variable

