# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RfBP8r1fnW1sSTY12VeTV96TlnVONLN8
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_csv('Salary_Data.csv',header='infer')

X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

print(X)
print(y)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#Linear Regression using sklearn
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
print(regressor.coef_)
print(regressor.intercept_)

#predicting the Values for X_test
y_pred = regressor.predict(X_test)
print(y_pred)

#Visualization for training data

plt.scatter(X_train, y_train, color='blue')
plt.plot(X_train, regressor.predict(X_train), color='red')
plt.title('Salary vs Age (Training data)')
plt.xlabel('Age')
plt.ylabel('Salary')

#Visualization for testing data

plt.scatter(X_test, y_test, color='blue')
plt.plot(X_train, regressor.predict(X_train), color='red')
plt.title('Salary vs Age (Testing data)')
plt.xlabel('Age')
plt.ylabel('Salary')

#Predict the salary of person having age 21 years

print(regressor.predict([[21]]))