# -*- coding: utf-8 -*-
"""Multiple_Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXiEHRwwRobZyGDPnuOadM6DjnABwoqO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('50_Startups.csv',header='infer')
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

#Encoding the Data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#Index is 3 because it has City names
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#IMport linear model
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)
print(regressor.coef_)
print(regressor.intercept_)

#Predict for X_test
X_pred = regressor.predict(X_test)

#For showing data upto 2 decimals only
np.set_printoptions(precision=2)
print(X_pred)

print(np.concatenate((X_pred.reshape(len(X_pred), 1), y_test.reshape(len(y_test), 1)), axis=1))

print(regressor.predict([[1, 0, 0, 160000, 130000, 300000]]))

plt.scatter(X_train[:,3], y_train[:], color='red')
plt.xlabel('R & D')
plt.ylabel('Profit')
plt.title('R&D vs Profit')

plt.scatter(X_train[:,4], y_train[:], color='blue')
plt.xlabel('Administration')
plt.ylabel('Profit')
plt.title('Administration vs Profit')

plt.scatter(X_train[:,5], y_train[:], color='yellow')
plt.xlabel('Marketing')
plt.ylabel('Profit')
plt.title('Marketing vs Profit')

