# -*- coding: utf-8 -*-
"""Polynomial_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dnewOYR8JNG3ElvSDyekKx-zbT7ZCC3A
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_csv('Position_Salaries.csv', header='infer')
X = data.iloc[:,1:-1].values
y = data.iloc[:,-1].values

from sklearn.linear_model import LinearRegression
line_reg = LinearRegression()
line_reg.fit(X, y)

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X)

line_reg2 = LinearRegression()
line_reg2.fit(X_poly, y)

#Scatter PLot
plt.scatter(X, y)

#Linear Regression
plt.plot(X, line_reg.predict(X), color='red')

#Polynomial Regression
plt.plot(X, line_reg2.predict(X_poly), color='yellow')

#Predicting value of 6.5

line_reg2.predict(poly_reg.fit_transform([[6.5]]))

