# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dWm4b-j4HFm5cMSa6SSLGbDhF2IhPylz
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_csv('Position_Salaries.csv', header='infer')
X = data.iloc[:,1:-1].values
y = data.iloc[:,-1].values

#Implimenting the RandomForest Regression model using sklearn
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state=0)
regressor.fit(X, y)

#Predicting with RandomForest Regression
regressor.predict([[6.5]])

#High Resolution visualizing the predicted data
X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor.predict(X_grid))
plt.title('Truth or Bluff (Random Forest)')
plt.xlabel('level')
plt.ylabel('Salary (10^6)')
plt.show()

